import pytest
import tempfile
import pathlib
import sys
import os
sys.path.append(
    os.path.abspath('examples/code/google_adk/agents/personalized-shopping/personalized_shopping/shared_libraries/web_agent_site')
)

from utils import random_idx, setup_logger, generate_mturk_code


def test_random_idx_basic():
    """Verify random_idx which validates indices within expected range for cumulative weights."""
    cum_weights = [2, 5 , 10]
    indices = [random_idx(cum_weights) for _ in range(1000)]
    assert all(idx in [0, 1, 2] for idx in indices), "Index should be either 0, 1, or 2"

def test_logging_file_output(tmp_path):
    """Verify that setup_logger creates a log file and writes log messages to it as expected."""
    session_id = "testsession"
    log_dir = tmp_path
    logger = setup_logger(session_id, log_dir)
    logger.info("Test log message")
    log_file = log_dir / f"{session_id}.jsonl"
    assert log_file.exists(), "Log file should be created"
    with open(log_file) as f:
        content = f.read()
    assert "Test log message" in content

def test_generate_mturk_code_format():
    """Verify the format of the MTurk code generated by generate_mturk_code."""
    code1 = generate_mturk_code("mysession")
    code2 = generate_mturk_code("mysession")
    assert code1 == code2, "Same session_id must give same code"
    assert len(code1) == 10, "Code should be of length 10"
    assert code1.isupper(), "Code should be uppercase hex"


